"""inspection tables

Revision ID: 35640a9085ca
Revises: a8fdb11311bc
Create Date: 2026-05-18 06:51:55.906154
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '35640a9085ca'
down_revision: str | None = 'a8fdb11311bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='inspection_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('expected_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirm_status', sa.Enum('pending', 'ok', 'mismatch', name='confirm_status'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_items_task_id'), 'inspection_items', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_items_task_id'), table_name='inspection_items')
    op.drop_table('inspection_items')
    op.drop_table('inspection_tasks')
    # ### end Alembic commands ###
    for _enum in ('inspection_status', 'confirm_status'):
        sa.Enum(name=_enum).drop(op.get_bind(), checkfirst=True)
