"""users and departments

Revision ID: a3e1b7402aaf
Revises: 0001_initial
Create Date: 2026-05-18 03:49:23.173481
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a3e1b7402aaf'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lark_department_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lark_department_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lark_open_id', sa.String(length=64), nullable=True),
    sa.Column('lark_union_id', sa.String(length=64), nullable=True),
    sa.Column('lark_user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('employee', 'manager', 'it_admin', 'procurement', 'finance', 'sys_admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lark_open_id'),
    sa.UniqueConstraint('lark_union_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_status').drop(op.get_bind(), checkfirst=True)
