"""approval requests

Revision ID: a51b2fe67785
Revises: 35640a9085ca
Create Date: 2026-05-18 07:20:55.546290
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a51b2fe67785'
down_revision: str | None = '35640a9085ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_no', sa.String(length=32), nullable=False),
    sa.Column('request_type', sa.Enum('consumable', 'asset', name='request_type'), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'fulfilled', name='approval_status'), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lark_message_id', sa.String(length=64), nullable=True),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_request_no'), 'approval_requests', ['request_no'], unique=True)
    op.create_index(op.f('ix_approval_requests_requester_id'), 'approval_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requester_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_request_no'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
    for _enum in ('request_type', 'approval_status'):
        sa.Enum(name=_enum).drop(op.get_bind(), checkfirst=True)
