"""inventory tables

Revision ID: a8fdb11311bc
Revises: c64bfdcd739b
Create Date: 2026-05-18 06:38:44.469844
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a8fdb11311bc'
down_revision: str | None = 'c64bfdcd739b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.Enum('purchase_in', 'issue', 'return_', 'transfer', 'adjustment', 'damage', 'scrap', name='order_type'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=True),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('source_location_id', sa.BigInteger(), nullable=True),
    sa.Column('target_location_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_orders_order_no'), 'inventory_orders', ['order_no'], unique=True)
    op.create_table('item_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('management_mode', sa.Enum('asset', 'inventory', 'consumable', 'accessory', name='management_mode'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('management_mode', sa.Enum('asset', 'inventory', 'consumable', 'accessory', name='management_mode'), nullable=False),
    sa.Column('need_approval', sa.Boolean(), nullable=False),
    sa.Column('need_return', sa.Boolean(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('monthly_use', sa.Integer(), nullable=True),
    sa.Column('default_location_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['default_location_id'], ['inventory_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_sku_code'), 'skus', ['sku_code'], unique=True)
    op.create_table('employee_item_issues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('issue_order_id', sa.BigInteger(), nullable=True),
    sa.Column('need_return', sa.Boolean(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'returned', 'consumed', 'lost', 'damaged', name='issue_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_item_issues_user_id'), 'employee_item_issues', ['user_id'], unique=False)
    op.create_table('inventory_order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['inventory_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_order_items_order_id'), 'inventory_order_items', ['order_id'], unique=False)
    op.create_table('inventory_stocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_locked', sa.Integer(), nullable=False),
    sa.Column('quantity_damaged', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'location_id', name='uq_stock_sku_loc')
    )
    op.create_index(op.f('ix_inventory_stocks_sku_id'), 'inventory_stocks', ['sku_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase_in', 'manual_in', 'issue_out', 'return_in', 'transfer_out', 'transfer_in', 'adjustment', 'damage_out', 'scrap_out', name='transaction_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('before_quantity', sa.Integer(), nullable=False),
    sa.Column('after_quantity', sa.Integer(), nullable=False),
    sa.Column('related_order_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_sku_id'), 'inventory_transactions', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_sku_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_stocks_sku_id'), table_name='inventory_stocks')
    op.drop_table('inventory_stocks')
    op.drop_index(op.f('ix_inventory_order_items_order_id'), table_name='inventory_order_items')
    op.drop_table('inventory_order_items')
    op.drop_index(op.f('ix_employee_item_issues_user_id'), table_name='employee_item_issues')
    op.drop_table('employee_item_issues')
    op.drop_index(op.f('ix_skus_sku_code'), table_name='skus')
    op.drop_table('skus')
    op.drop_table('item_categories')
    op.drop_index(op.f('ix_inventory_orders_order_no'), table_name='inventory_orders')
    op.drop_table('inventory_orders')
    op.drop_table('inventory_locations')
    # ### end Alembic commands ###
    for _enum in ('management_mode', 'transaction_type', 'order_type', 'issue_status'):
        sa.Enum(name=_enum).drop(op.get_bind(), checkfirst=True)
